import type { ServiceDefinition } from './service-detection.types';

export const GENERIC_ICON_NAME = 'generic';
export const GENERIC_SERVICE_ID = 'generic';

export const SERVICE_ICON_GLYPHS: Record<string, string> = {
  generic: '*',
  steam: 'S',
  github: 'G',
  gitlab: 'GL',
  google: 'Go',
  gmail: 'GM',
  youtube: 'YT',
  discord: 'D',
  reddit: 'R',
  twitch: 'Tw',
  amazon: 'A',
  paypal: 'P',
  binance: 'B',
  twitterx: 'X',
  facebook: 'F',
  instagram: 'IG',
  linkedin: 'IN',
  microsoft: 'MS',
  outlook: 'OL',
  dropbox: 'DB',
  mega: 'M',
  notion: 'N',
  openai: 'OA',
  chatgpt: 'CG',
  riotgames: 'RG',
  epicgames: 'EG',
  ubisoft: 'U',
  ea: 'EA',
  spotify: 'Sp',
  netflix: 'Nf',
  disneyplus: 'D+',
  primevideo: 'PV',
  apple: 'Ap',
  icloud: 'IC',
  jira: 'Ji',
  confluence: 'Co',
  trello: 'Tr',
  bitbucket: 'BB',
  atlassian: 'At',
  figma: 'Fi',
  zoom: 'Zm',
  telegram: 'Tg',
  whatsapp: 'Wa',
  protonmail: 'PM',
  tiktok: 'TT',
  pinterest: 'Pn',
  roblox: 'Rb',
  battlenet: 'BN',
  playstation: 'Ps',
  docker: 'Do',
  chrome: 'Ch',
  firefox: 'Fx',
  opera: 'Op',
  brave: 'Br',
  onepassword: '1P',
  lastpass: 'LP',
  bitwarden: 'BW',
  coinbase: 'Cb',
  stripe: 'St',
  patreon: 'Pa',
  evernote: 'Ev',
  obsidian: 'Ob',
  linear: 'Li',
  vercel: 'Ve',
  netlify: 'Ne',
  snapchat: 'Sc',
  skype: 'Sk',
  teams: 'Tm',
  adobe: 'Ad',
  yahoo: 'Ya',
  yahoomail: 'YM',
  aws: 'AWS',
  cloudflare: 'CF',
  digitalocean: 'DO',
  heroku: 'He',
  railway: 'Rw',
  render: 'Re',
  supabase: 'Su',
  firebase: 'Fb',
  planetscale: 'PS',
  mongodb: 'Mg',
  postgresql: 'Pg',
  xbox: 'XB',
  nintendo: 'Ni',
  rockstar: 'RS',
  genshin: 'Ge',
  minecraft: 'Mc',
  valorant: 'Va',
  kraken: 'Kr',
  metamask: 'MM',
  trustwallet: 'TW',
  ledger: 'Le',
  revolut: 'Rv',
  wise: 'Wi',
  hbo: 'HBO',
  hbomax: 'HM',
  paramountplus: 'P+',
  appletv: 'TV',
  proton: 'Pr',
  zoho: 'Zo',
  fastmail: 'Fm',
  icloudmail: 'IM',
  onedrive: 'OD',
  googledrive: 'GD',
  box: 'Bx',
  anthropic: 'An',
  claude: 'Cl',
  perplexity: 'Px',
  midjourney: 'Mj',
  huggingface: 'HF',
  replicate: 'Rp',
  canva: 'Ca',
  monday: 'Mo',
  asana: 'As',
  clickup: 'Cu',
  todoist: 'To',
  airtable: 'Atb'
};

export const SERVICE_ICON_ASSETS: Record<string, string> = {
  steam: 'assets/icons/services/steam.svg',
  github: 'assets/icons/services/github.svg',
  gitlab: 'assets/icons/services/gitlab.svg',
  google: 'assets/icons/services/google.svg',
  gmail: 'assets/icons/services/gmail.svg',
  youtube: 'assets/icons/services/youtube.svg',
  discord: 'assets/icons/services/discord.svg',
  reddit: 'assets/icons/services/reddit.svg',
  twitch: 'assets/icons/services/twitch.svg',
  paypal: 'assets/icons/services/paypal.svg',
  binance: 'assets/icons/services/binance.svg',
  twitterx: 'assets/icons/services/twitterx.svg',
  facebook: 'assets/icons/services/facebook.svg',
  instagram: 'assets/icons/services/instagram.svg',
  linkedin: 'assets/icons/services/linkedin.svg',
  dropbox: 'assets/icons/services/dropbox.svg',
  mega: 'assets/icons/services/mega.svg',
  notion: 'assets/icons/services/notion.svg',
  riotgames: 'assets/icons/services/riotgames.svg',
  epicgames: 'assets/icons/services/epicgames.svg',
  ubisoft: 'assets/icons/services/ubisoft.svg',
  ea: 'assets/icons/services/ea.svg',
  spotify: 'assets/icons/services/spotify.svg',
  netflix: 'assets/icons/services/netflix.svg',
  apple: 'assets/icons/services/apple.svg',
  icloud: 'assets/icons/services/icloud.svg',
  jira: 'assets/icons/services/jira.svg',
  confluence: 'assets/icons/services/confluence.svg',
  trello: 'assets/icons/services/trello.svg',
  bitbucket: 'assets/icons/services/bitbucket.svg',
  atlassian: 'assets/icons/services/atlassian.svg',
  figma: 'assets/icons/services/figma.svg',
  zoom: 'assets/icons/services/zoom.svg',
  telegram: 'assets/icons/services/telegram.svg',
  whatsapp: 'assets/icons/services/whatsapp.svg',
  protonmail: 'assets/icons/services/protonmail.svg',
  tiktok: 'assets/icons/services/tiktok.svg',
  pinterest: 'assets/icons/services/pinterest.svg',
  roblox: 'assets/icons/services/roblox.svg',
  battlenet: 'assets/icons/services/battlenet.svg',
  playstation: 'assets/icons/services/playstation.svg',
  docker: 'assets/icons/services/docker.svg',
  chrome: 'assets/icons/services/chrome.svg',
  firefox: 'assets/icons/services/firefox.svg',
  opera: 'assets/icons/services/opera.svg',
  brave: 'assets/icons/services/brave.svg',
  onepassword: 'assets/icons/services/onepassword.svg',
  lastpass: 'assets/icons/services/lastpass.svg',
  bitwarden: 'assets/icons/services/bitwarden.svg',
  coinbase: 'assets/icons/services/coinbase.svg',
  stripe: 'assets/icons/services/stripe.svg',
  patreon: 'assets/icons/services/patreon.svg',
  evernote: 'assets/icons/services/evernote.svg',
  obsidian: 'assets/icons/services/obsidian.svg',
  linear: 'assets/icons/services/linear.svg',
  vercel: 'assets/icons/services/vercel.svg',
  netlify: 'assets/icons/services/netlify.svg',
  snapchat: 'assets/icons/services/snapchat.svg',
  cloudflare: 'assets/icons/services/cloudflare.svg',
  digitalocean: 'assets/icons/services/digitalocean.svg',
  railway: 'assets/icons/services/railway.svg',
  render: 'assets/icons/services/render.svg',
  supabase: 'assets/icons/services/supabase.svg',
  firebase: 'assets/icons/services/firebase.svg',
  planetscale: 'assets/icons/services/planetscale.svg',
  mongodb: 'assets/icons/services/mongodb.svg',
  postgresql: 'assets/icons/services/postgresql.svg',
  rockstar: 'assets/icons/services/rockstar.svg',
  valorant: 'assets/icons/services/valorant.svg',
  kraken: 'assets/icons/services/kraken.svg',
  revolut: 'assets/icons/services/revolut.svg',
  wise: 'assets/icons/services/wise.svg',
  hbo: 'assets/icons/services/hbo.svg',
  hbomax: 'assets/icons/services/hbomax.svg',
  paramountplus: 'assets/icons/services/paramountplus.svg',
  appletv: 'assets/icons/services/appletv.svg',
  proton: 'assets/icons/services/proton.svg',
  zoho: 'assets/icons/services/zoho.svg',
  googledrive: 'assets/icons/services/googledrive.svg',
  box: 'assets/icons/services/box.svg',
  anthropic: 'assets/icons/services/anthropic.svg',
  claude: 'assets/icons/services/claude.svg',
  perplexity: 'assets/icons/services/perplexity.svg',
  huggingface: 'assets/icons/services/huggingface.svg',
  replicate: 'assets/icons/services/replicate.svg',
  canva: 'assets/icons/services/canva.svg',
  asana: 'assets/icons/services/asana.svg',
  clickup: 'assets/icons/services/clickup.svg',
  todoist: 'assets/icons/services/todoist.svg',
  airtable: 'assets/icons/services/airtable.svg'
};

export const SERVICE_ICON_REGISTRY: ServiceDefinition[] = [
  { id: 'steam', displayName: 'Steam', iconName: 'steam', domains: ['steampowered.com', 'steamcommunity.com'], keywords: ['steam'], aliases: [], priority: 80 },
  { id: 'github', displayName: 'GitHub', iconName: 'github', domains: ['github.com'], keywords: ['github'], aliases: ['gh'], priority: 70 },
  { id: 'gitlab', displayName: 'GitLab', iconName: 'gitlab', domains: ['gitlab.com'], keywords: ['gitlab'], aliases: [], priority: 70 },
  { id: 'gmail', displayName: 'Gmail', iconName: 'gmail', domains: ['gmail.com', 'mail.google.com'], emailDomains: ['gmail.com'], keywords: ['gmail'], aliases: ['google mail'], priority: 92 },
  { id: 'google', displayName: 'Google', iconName: 'google', domains: ['google.com'], keywords: ['google'], aliases: [], priority: 75 },
  { id: 'youtube', displayName: 'YouTube', iconName: 'youtube', domains: ['youtube.com', 'youtu.be'], keywords: ['youtube'], aliases: ['yt'], priority: 75 },
  { id: 'discord', displayName: 'Discord', iconName: 'discord', domains: ['discord.com', 'discord.gg'], keywords: ['discord'], aliases: [], priority: 70 },
  { id: 'reddit', displayName: 'Reddit', iconName: 'reddit', domains: ['reddit.com'], keywords: ['reddit'], aliases: ['subreddit'], priority: 70 },
  { id: 'twitch', displayName: 'Twitch', iconName: 'twitch', domains: ['twitch.tv'], keywords: ['twitch'], aliases: [], priority: 70 },
  { id: 'amazon', displayName: 'Amazon', iconName: 'amazon', domains: ['amazon.com', 'amazon.es', 'amazon.co.uk'], keywords: ['amazon'], aliases: [], priority: 70 },
  { id: 'paypal', displayName: 'PayPal', iconName: 'paypal', domains: ['paypal.com'], keywords: ['paypal'], aliases: [], priority: 70 },
  { id: 'binance', displayName: 'Binance', iconName: 'binance', domains: ['binance.com'], keywords: ['binance'], aliases: ['binance spot', 'binance futures'], priority: 80 },
  { id: 'twitterx', displayName: 'X / Twitter', iconName: 'twitterx', domains: ['twitter.com', 'x.com'], keywords: ['twitter'], aliases: ['tweetdeck'], priority: 70 },
  { id: 'facebook', displayName: 'Facebook', iconName: 'facebook', domains: ['facebook.com', 'fb.com'], keywords: ['facebook'], aliases: ['fb'], priority: 70 },
  { id: 'instagram', displayName: 'Instagram', iconName: 'instagram', domains: ['instagram.com'], keywords: ['instagram'], aliases: ['insta'], priority: 70 },
  { id: 'linkedin', displayName: 'LinkedIn', iconName: 'linkedin', domains: ['linkedin.com'], keywords: ['linkedin'], aliases: ['linked in'], priority: 70 },
  { id: 'microsoft', displayName: 'Microsoft', iconName: 'microsoft', domains: ['microsoft.com'], keywords: ['microsoft'], aliases: ['ms'], priority: 68 },
  { id: 'outlook', displayName: 'Outlook', iconName: 'outlook', domains: ['outlook.com', 'live.com', 'hotmail.com'], emailDomains: ['outlook.com', 'live.com', 'hotmail.com'], keywords: ['outlook', 'hotmail'], aliases: ['microsoft mail'], priority: 88 },
  { id: 'dropbox', displayName: 'Dropbox', iconName: 'dropbox', domains: ['dropbox.com'], keywords: ['dropbox'], aliases: [], priority: 70 },
  { id: 'mega', displayName: 'Mega', iconName: 'mega', domains: ['mega.nz'], keywords: ['mega'], aliases: [], priority: 68 },
  { id: 'notion', displayName: 'Notion', iconName: 'notion', domains: ['notion.so'], keywords: ['notion'], aliases: [], priority: 70 },
  { id: 'chatgpt', displayName: 'ChatGPT', iconName: 'chatgpt', domains: ['chatgpt.com', 'chat.openai.com'], keywords: ['chatgpt'], aliases: ['chat gpt'], priority: 95 },
  { id: 'openai', displayName: 'OpenAI', iconName: 'openai', domains: ['openai.com'], keywords: ['openai'], aliases: [], priority: 80 },
  { id: 'riotgames', displayName: 'Riot Games', iconName: 'riotgames', domains: ['riotgames.com'], keywords: ['riot games', 'riot'], aliases: ['valorant', 'league of legends'], priority: 75 },
  { id: 'epicgames', displayName: 'Epic Games', iconName: 'epicgames', domains: ['epicgames.com'], keywords: ['epic games'], aliases: ['epic'], priority: 72 },
  { id: 'ubisoft', displayName: 'Ubisoft', iconName: 'ubisoft', domains: ['ubisoft.com'], keywords: ['ubisoft'], aliases: ['uplay'], priority: 72 },
  { id: 'ea', displayName: 'EA', iconName: 'ea', domains: ['ea.com'], keywords: ['electronic arts'], aliases: ['ea app', 'origin'], priority: 72 },
  { id: 'spotify', displayName: 'Spotify', iconName: 'spotify', domains: ['spotify.com'], keywords: ['spotify'], aliases: [], priority: 70 },
  { id: 'netflix', displayName: 'Netflix', iconName: 'netflix', domains: ['netflix.com'], keywords: ['netflix'], aliases: [], priority: 70 },
  { id: 'disneyplus', displayName: 'Disney+', iconName: 'disneyplus', domains: ['disneyplus.com'], keywords: ['disney+'], aliases: ['disney plus'], priority: 72 },
  { id: 'primevideo', displayName: 'Prime Video', iconName: 'primevideo', domains: ['primevideo.com'], keywords: ['prime video'], aliases: ['amazon prime video'], priority: 74 },
  { id: 'apple', displayName: 'Apple', iconName: 'apple', domains: ['apple.com'], keywords: ['apple'], aliases: ['apple id'], priority: 78 },
  { id: 'icloud', displayName: 'iCloud', iconName: 'icloud', domains: ['icloud.com'], keywords: ['icloud'], aliases: ['apple cloud'], priority: 86 },
  { id: 'jira', displayName: 'Jira', iconName: 'jira', domains: ['atlassian.net', 'jira.com'], keywords: ['jira'], aliases: ['jira cloud'], priority: 82 },
  { id: 'confluence', displayName: 'Confluence', iconName: 'confluence', domains: ['atlassian.net', 'confluence.atlassian.com'], keywords: ['confluence'], aliases: [], priority: 78 },
  { id: 'trello', displayName: 'Trello', iconName: 'trello', domains: ['trello.com'], keywords: ['trello'], aliases: [], priority: 76 },
  { id: 'bitbucket', displayName: 'Bitbucket', iconName: 'bitbucket', domains: ['bitbucket.org'], keywords: ['bitbucket'], aliases: [], priority: 76 },
  { id: 'atlassian', displayName: 'Atlassian', iconName: 'atlassian', domains: ['atlassian.com'], keywords: ['atlassian'], aliases: [], priority: 72 },
  { id: 'figma', displayName: 'Figma', iconName: 'figma', domains: ['figma.com'], keywords: ['figma'], aliases: [], priority: 75 },
  { id: 'zoom', displayName: 'Zoom', iconName: 'zoom', domains: ['zoom.us'], keywords: ['zoom'], aliases: ['zoom meetings'], priority: 75 },
  { id: 'telegram', displayName: 'Telegram', iconName: 'telegram', domains: ['telegram.org', 't.me'], keywords: ['telegram'], aliases: [], priority: 74 },
  { id: 'whatsapp', displayName: 'WhatsApp', iconName: 'whatsapp', domains: ['whatsapp.com'], keywords: ['whatsapp'], aliases: [], priority: 74 },
  { id: 'protonmail', displayName: 'Proton Mail', iconName: 'protonmail', domains: ['proton.me', 'protonmail.com'], emailDomains: ['proton.me', 'protonmail.com'], keywords: ['proton', 'proton mail'], aliases: [], priority: 82 },
  { id: 'tiktok', displayName: 'TikTok', iconName: 'tiktok', domains: ['tiktok.com'], keywords: ['tiktok'], aliases: [], priority: 73 },
  { id: 'pinterest', displayName: 'Pinterest', iconName: 'pinterest', domains: ['pinterest.com'], keywords: ['pinterest'], aliases: [], priority: 73 },
  { id: 'roblox', displayName: 'Roblox', iconName: 'roblox', domains: ['roblox.com'], keywords: ['roblox'], aliases: [], priority: 72 },
  { id: 'battlenet', displayName: 'Battle.net', iconName: 'battlenet', domains: ['battle.net', 'blizzard.com'], keywords: ['battle.net'], aliases: ['battlenet', 'blizzard'], priority: 80 },
  { id: 'playstation', displayName: 'PlayStation', iconName: 'playstation', domains: ['playstation.com'], keywords: ['playstation'], aliases: ['psn'], priority: 74 },
  { id: 'docker', displayName: 'Docker', iconName: 'docker', domains: ['docker.com', 'hub.docker.com'], keywords: ['docker'], aliases: ['docker hub'], priority: 74 },
  { id: 'chrome', displayName: 'Google Chrome', iconName: 'chrome', domains: ['chrome.google.com'], keywords: ['chrome'], aliases: ['google chrome'], priority: 70 },
  { id: 'firefox', displayName: 'Firefox', iconName: 'firefox', domains: ['firefox.com', 'mozilla.org'], keywords: ['firefox'], aliases: ['mozilla firefox'], priority: 70 },
  { id: 'opera', displayName: 'Opera', iconName: 'opera', domains: ['opera.com'], keywords: ['opera'], aliases: ['opera gx'], priority: 70 },
  { id: 'brave', displayName: 'Brave', iconName: 'brave', domains: ['brave.com'], keywords: ['brave'], aliases: ['brave browser'], priority: 70 },
  { id: 'onepassword', displayName: '1Password', iconName: 'onepassword', domains: ['1password.com'], keywords: ['1password'], aliases: ['onepassword'], priority: 74 },
  { id: 'lastpass', displayName: 'LastPass', iconName: 'lastpass', domains: ['lastpass.com'], keywords: ['lastpass'], aliases: [], priority: 72 },
  { id: 'bitwarden', displayName: 'Bitwarden', iconName: 'bitwarden', domains: ['bitwarden.com'], keywords: ['bitwarden'], aliases: [], priority: 72 },
  { id: 'coinbase', displayName: 'Coinbase', iconName: 'coinbase', domains: ['coinbase.com'], keywords: ['coinbase'], aliases: [], priority: 74 },
  { id: 'stripe', displayName: 'Stripe', iconName: 'stripe', domains: ['stripe.com'], keywords: ['stripe'], aliases: [], priority: 72 },
  { id: 'patreon', displayName: 'Patreon', iconName: 'patreon', domains: ['patreon.com'], keywords: ['patreon'], aliases: [], priority: 72 },
  { id: 'evernote', displayName: 'Evernote', iconName: 'evernote', domains: ['evernote.com'], keywords: ['evernote'], aliases: [], priority: 70 },
  { id: 'obsidian', displayName: 'Obsidian', iconName: 'obsidian', domains: ['obsidian.md'], keywords: ['obsidian'], aliases: [], priority: 70 },
  { id: 'linear', displayName: 'Linear', iconName: 'linear', domains: ['linear.app'], keywords: ['linear'], aliases: [], priority: 70 },
  { id: 'vercel', displayName: 'Vercel', iconName: 'vercel', domains: ['vercel.com'], keywords: ['vercel'], aliases: [], priority: 70 },
  { id: 'netlify', displayName: 'Netlify', iconName: 'netlify', domains: ['netlify.com'], keywords: ['netlify'], aliases: [], priority: 70 },
  { id: 'snapchat', displayName: 'Snapchat', iconName: 'snapchat', domains: ['snapchat.com'], keywords: ['snapchat'], aliases: [], priority: 70 },
  { id: 'skype', displayName: 'Skype', iconName: 'skype', domains: ['skype.com'], keywords: ['skype'], aliases: [], priority: 70 },
  { id: 'teams', displayName: 'Microsoft Teams', iconName: 'teams', domains: ['teams.microsoft.com'], keywords: ['teams', 'microsoft teams'], aliases: [], priority: 76 },
  { id: 'adobe', displayName: 'Adobe', iconName: 'adobe', domains: ['adobe.com'], keywords: ['adobe'], aliases: ['creative cloud'], priority: 70 },
  { id: 'yahoo', displayName: 'Yahoo', iconName: 'yahoo', domains: ['yahoo.com'], keywords: ['yahoo'], aliases: [], priority: 68 },
  { id: 'yahoomail', displayName: 'Yahoo Mail', iconName: 'yahoomail', domains: ['mail.yahoo.com'], emailDomains: ['yahoo.com', 'yahoo.es', 'ymail.com'], keywords: ['yahoo mail'], aliases: ['ymail'], priority: 84 },
  { id: 'aws', displayName: 'AWS', iconName: 'aws', domains: ['amazonaws.com', 'aws.amazon.com'], keywords: ['aws', 'amazon web services'], aliases: [], priority: 74 },
  { id: 'cloudflare', displayName: 'Cloudflare', iconName: 'cloudflare', domains: ['cloudflare.com'], keywords: ['cloudflare'], aliases: [], priority: 74 },
  { id: 'digitalocean', displayName: 'DigitalOcean', iconName: 'digitalocean', domains: ['digitalocean.com'], keywords: ['digitalocean'], aliases: ['do'], priority: 72 },
  { id: 'heroku', displayName: 'Heroku', iconName: 'heroku', domains: ['heroku.com'], keywords: ['heroku'], aliases: [], priority: 70 },
  { id: 'railway', displayName: 'Railway', iconName: 'railway', domains: ['railway.app'], keywords: ['railway'], aliases: [], priority: 70 },
  { id: 'render', displayName: 'Render', iconName: 'render', domains: ['render.com'], keywords: ['render'], aliases: [], priority: 70 },
  { id: 'supabase', displayName: 'Supabase', iconName: 'supabase', domains: ['supabase.com'], keywords: ['supabase'], aliases: [], priority: 72 },
  { id: 'firebase', displayName: 'Firebase', iconName: 'firebase', domains: ['firebase.google.com'], keywords: ['firebase'], aliases: [], priority: 72 },
  { id: 'planetscale', displayName: 'PlanetScale', iconName: 'planetscale', domains: ['planetscale.com'], keywords: ['planetscale'], aliases: [], priority: 70 },
  { id: 'mongodb', displayName: 'MongoDB', iconName: 'mongodb', domains: ['mongodb.com'], keywords: ['mongodb', 'mongo'], aliases: [], priority: 72 },
  { id: 'postgresql', displayName: 'PostgreSQL', iconName: 'postgresql', domains: ['postgresql.org'], keywords: ['postgresql', 'postgres'], aliases: [], priority: 70 },
  { id: 'xbox', displayName: 'Xbox', iconName: 'xbox', domains: ['xbox.com'], keywords: ['xbox'], aliases: ['xbox live'], priority: 72 },
  { id: 'nintendo', displayName: 'Nintendo', iconName: 'nintendo', domains: ['nintendo.com'], keywords: ['nintendo'], aliases: [], priority: 70 },
  { id: 'rockstar', displayName: 'Rockstar Games', iconName: 'rockstar', domains: ['rockstargames.com'], keywords: ['rockstar', 'rockstar games'], aliases: ['gta online'], priority: 74 },
  { id: 'genshin', displayName: 'Genshin Impact', iconName: 'genshin', domains: ['hoyoverse.com', 'mihoyo.com'], keywords: ['genshin', 'genshin impact'], aliases: ['hoyoverse'], priority: 72 },
  { id: 'minecraft', displayName: 'Minecraft', iconName: 'minecraft', domains: ['minecraft.net'], keywords: ['minecraft'], aliases: [], priority: 72 },
  { id: 'valorant', displayName: 'Valorant', iconName: 'valorant', domains: ['playvalorant.com'], keywords: ['valorant'], aliases: [], priority: 74 },
  { id: 'kraken', displayName: 'Kraken', iconName: 'kraken', domains: ['kraken.com'], keywords: ['kraken'], aliases: [], priority: 74 },
  { id: 'metamask', displayName: 'MetaMask', iconName: 'metamask', domains: ['metamask.io'], keywords: ['metamask'], aliases: [], priority: 74 },
  { id: 'trustwallet', displayName: 'Trust Wallet', iconName: 'trustwallet', domains: ['trustwallet.com'], keywords: ['trust wallet'], aliases: ['trustwallet'], priority: 74 },
  { id: 'ledger', displayName: 'Ledger', iconName: 'ledger', domains: ['ledger.com'], keywords: ['ledger'], aliases: [], priority: 72 },
  { id: 'revolut', displayName: 'Revolut', iconName: 'revolut', domains: ['revolut.com'], keywords: ['revolut'], aliases: [], priority: 72 },
  { id: 'wise', displayName: 'Wise', iconName: 'wise', domains: ['wise.com'], keywords: ['wise'], aliases: ['transferwise'], priority: 72 },
  { id: 'hbo', displayName: 'HBO', iconName: 'hbo', domains: ['hbo.com'], keywords: ['hbo'], aliases: [], priority: 70 },
  { id: 'hbomax', displayName: 'HBO Max', iconName: 'hbomax', domains: ['hbomax.com', 'max.com'], keywords: ['hbo max'], aliases: ['max'], priority: 76 },
  { id: 'paramountplus', displayName: 'Paramount+', iconName: 'paramountplus', domains: ['paramountplus.com'], keywords: ['paramount+', 'paramount plus'], aliases: [], priority: 72 },
  { id: 'appletv', displayName: 'Apple TV', iconName: 'appletv', domains: ['tv.apple.com'], keywords: ['apple tv'], aliases: [], priority: 72 },
  { id: 'proton', displayName: 'Proton', iconName: 'proton', domains: ['proton.me'], keywords: ['proton'], aliases: ['protonmail'], priority: 72 },
  { id: 'zoho', displayName: 'Zoho', iconName: 'zoho', domains: ['zoho.com'], keywords: ['zoho'], aliases: [], priority: 70 },
  { id: 'fastmail', displayName: 'Fastmail', iconName: 'fastmail', domains: ['fastmail.com'], emailDomains: ['fastmail.com', 'fastmail.fm'], keywords: ['fastmail'], aliases: [], priority: 70 },
  { id: 'icloudmail', displayName: 'iCloud Mail', iconName: 'icloudmail', domains: ['icloud.com'], emailDomains: ['icloud.com', 'me.com', 'mac.com'], keywords: ['icloud mail'], aliases: [], priority: 82 },
  { id: 'onedrive', displayName: 'OneDrive', iconName: 'onedrive', domains: ['onedrive.live.com'], keywords: ['onedrive'], aliases: ['one drive'], priority: 72 },
  { id: 'googledrive', displayName: 'Google Drive', iconName: 'googledrive', domains: ['drive.google.com'], keywords: ['google drive'], aliases: ['gdrive'], priority: 72 },
  { id: 'box', displayName: 'Box', iconName: 'box', domains: ['box.com'], keywords: ['box'], aliases: ['box drive'], priority: 70 },
  { id: 'anthropic', displayName: 'Anthropic', iconName: 'anthropic', domains: ['anthropic.com'], keywords: ['anthropic'], aliases: [], priority: 74 },
  { id: 'claude', displayName: 'Claude', iconName: 'claude', domains: ['claude.ai'], keywords: ['claude'], aliases: [], priority: 80 },
  { id: 'perplexity', displayName: 'Perplexity', iconName: 'perplexity', domains: ['perplexity.ai'], keywords: ['perplexity'], aliases: [], priority: 74 },
  { id: 'midjourney', displayName: 'Midjourney', iconName: 'midjourney', domains: ['midjourney.com'], keywords: ['midjourney'], aliases: [], priority: 72 },
  { id: 'huggingface', displayName: 'Hugging Face', iconName: 'huggingface', domains: ['huggingface.co'], keywords: ['hugging face', 'huggingface'], aliases: ['hf'], priority: 74 },
  { id: 'replicate', displayName: 'Replicate', iconName: 'replicate', domains: ['replicate.com'], keywords: ['replicate'], aliases: [], priority: 72 },
  { id: 'canva', displayName: 'Canva', iconName: 'canva', domains: ['canva.com'], keywords: ['canva'], aliases: [], priority: 72 },
  { id: 'monday', displayName: 'monday.com', iconName: 'monday', domains: ['monday.com'], keywords: ['monday.com', 'monday'], aliases: [], priority: 70 },
  { id: 'asana', displayName: 'Asana', iconName: 'asana', domains: ['asana.com'], keywords: ['asana'], aliases: [], priority: 70 },
  { id: 'clickup', displayName: 'ClickUp', iconName: 'clickup', domains: ['clickup.com'], keywords: ['clickup'], aliases: ['click up'], priority: 72 },
  { id: 'todoist', displayName: 'Todoist', iconName: 'todoist', domains: ['todoist.com'], keywords: ['todoist'], aliases: [], priority: 70 },
  { id: 'airtable', displayName: 'Airtable', iconName: 'airtable', domains: ['airtable.com'], keywords: ['airtable'], aliases: [], priority: 70 }
];

